export const theme = {
  colors: {
    primaryColor: '#0A1128',
    secondaryColor: 'crimson',
    white: '#FFFFFF',
    mediumGray: '#DDDDDD',
    crimson: 'crimson',
    blue: 'rgb(36, 36, 209)',
    navy: '#0A1128',
    black: '#000000',
    pink: 'rgb(231, 171, 181)',
    purple: 'rgb(133, 21, 133)',
    orange: 'rgb(230, 159, 28)',
    green: 'rgb(29, 161, 29)',
    lightBlue: 'rgb(146, 195, 211)',
    yellow: 'rgb(207, 207, 45)',
    brown: 'rgb(116, 45, 45)',
    grey: '#DDDDDD',
  },
  font: {
    family: {
      default: "'Montserrat', sans-serif",
    },
    sizes: {
      xsmall: '0.8rem',
      small: '1.6rem',
      gtsmall: '1.8rem',
      ltmedium: '2rem',
      medium: '2.4rem',
      ltlarge: '2.8rem',
      large: '3.2rem',
      xlarge: '4.0rem',
      xxlarge: '4.8rem',
      huge: '5.6rem',
      xhuge: '6.4rem',
    },
  },
  media: {
    lteMedium: '(max-width: 768px)',
    gteMedium: '(min-width: 768px)',
    lteSmall: '(max-width: 440px)',
    gteSmall: '(min-width: 440px)',
  },
  spacings: {
    xxsmall: '0.4rem',
    xsmall: '0.8rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    xxlarge: '4.8rem',
    huge: '5.6rem',
    xhuge: '6.4rem',
  },
  frameSizes: {
    tiny: '8rem',
    xxsmall: '12rem',
    ltxsmall: '15rem',
    xsmall: '18rem',
    ltsmall: '21rem',
    small: '24rem',
    gtsmall: '28rem',
    smallMedium: '32rem',
    ltmedium: '36rem',
    medium: '40rem',
    largeMedium: '56rem',
    large: '64rem',
    xlarge: '80rem',
    xxlarge: '104rem',
    max: '120rem',
  },
  transitions: {
    fastest: 'all 100ms ease-in-out',
    faster: 'all 200ms ease-in-out',
    fast: 'all 300ms ease-in-out',
    normal: 'all 500ms ease-in-out',
    slow: 'all 600ms ease-in-out',
    slower: 'all 800ms ease-in-out',
    slowest: 'all 1s ease-in-out',
  },
} as const;
